apiVersion: batch/v1
kind: Job
metadata:
  name: eks-delete-cluster-job
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: eks-manager
    spec:
      restartPolicy: Never
      containers:
        - name: eks-manager
          image: eks-manager:v1
          command: ["eks", "cluster", "delete"]
          env:
            - name: EKS_CLUSTER_NAME
              value: "the-cluster"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
