apiVersion: v1
kind: Pod
metadata:
  name: connectivity-check
spec:
  containers:
    - name: check-internet
      image: busybox
      command:
        - sh
        - -c
        - "while true; do sleep 3600; done"

