apiVersion: batch/v1
kind: Job
metadata:
  name: eks-create-cluster-job
spec:
  template:
    metadata:
      labels:
        app: eks-manager
    spec:
      containers:
        - name: eks-manager
          image: eks-manager:v1
          command: ["eks"]
          args: ["cluster", "create"]
          env:
            # Common Options
            - name: EKS_CLUSTER_NAME
              value: None 
            - name: EKS_ENVIRONMENT
              value: "dev" 
            - name: EKS_REGION
              value: "us-east-1" 
            - name: EKS_ORGNIZATION
              value: "default" 
            - name: EKS_VPC_NAME
              value: None 
            - name: EKS_CLUSTER_BOOTSTRAP_ADMIN
              value: "True" 
            - name: EKS_CLUSTER_IP_FAMILY
              value: "ipv4" 
            - name: EKS_CLUSTER_VERSION
              value: None 
            - name: EKS_CLUSTER_PUBLIC_PRIVATE_ACCESS
              value: "both" 
            - name: EKS_CLUSTER_SECURITY_GROUPS
              value: None 
            - name: EKS_CLUSTER_TAGS
              value: None 
            - name: EKS_CLUSTER_KUBERNETES_CIDR_BLOCK
              value: None 
            - name: EKS_CLUSTER_KMS_ENCRYPTION_KEY
              value: None 
            - name: EKS_CLUSTER_LOGGING_TYPES
              value: ""
            - name: EKS_PUBLIC_ACCESS_CIDRS
              value: None 
            - name: EKS_ROLE_ARN
              value: None 
            - name: EKS_SUPPORT_TYPE
              value: "STANDARD" 

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"

          volumeMounts:
            - name: state-volume
              mountPath: /app/state   # Mount the `/state` directory for testing
      volumes:
        - name: state-volume
          hostPath:
            path: /home/ryan/Projects/eks-manager/state
            type: Directory
      restartPolicy: Never
