apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: lab-dev-us-east-1-lab-cluster
  region: us-east-1
  version: '1.24'
vpc:
  id: vpc-065c711ee6db4f263
  subnets:
    public: {}
    private:
      us-east-1c:
        id: subnet-02bafaec63db63bc3
      us-east-1a:
        id: subnet-08002c6ca36513e93
      us-east-1b:
        id: subnet-0eaa654c78bb87a38
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: alb-ctrlr
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: autoscaler
      namespace: cluster-autoscaler
      labels:
        aws-usage: cluster-ops
    wellKnownPolicies:
      autoScaler: true
addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true
cloudWatch:
  clusterLogging:
    enableTypes:
    - api
    - audit
    - authenticator
    - controllerManager
    - scheduler
fargateProfiles:
- name: fp-kube-system
  selectors:
  - namespace: kube-system
  subnets:
  - subnet-0b474f10ac15eeee4
  - subnet-0d1f86103ab9ce83c
  - subnet-0cdeddb077945a74f
  - subnet-0eaa654c78bb87a38
  - subnet-02bafaec63db63bc3
  - subnet-08002c6ca36513e93
- name: fp-cluster-autoscaler
  selectors:
  - namespace: cluster-autoscaler
  subnets:
  - subnet-0b474f10ac15eeee4
  - subnet-0d1f86103ab9ce83c
  - subnet-0cdeddb077945a74f
  - subnet-0eaa654c78bb87a38
  - subnet-02bafaec63db63bc3
  - subnet-08002c6ca36513e93
